import { useCallback } from 'react';
import { getGetAutomationFlagsQueryOptions, setAutomationFlag } from '@workspace/api-client-react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { SystemStatusBanner } from './SystemStatusBanner';

/**
 * Automation kill switch UI — P17.1.
 *
 * P17.1 requires a *persistent, non-dismissible* critical banner when automation
 * is paused, carrying a Resume action, plus a polite announcement. The
 * SystemStatusBanner `critical` tone already enforces non-dismissible + assertive.
 *
 * Contract generated by Orval from lib/api-spec/openapi.yaml:
 *   GET /api/automation/flags       -> AutomationFlags { flags, paused }
 *   PUT /api/automation/flags/{key} -> SetAutomationFlag200 { flag }
 *
 * The `key` param is a generated enum (AutomationFlagKey = reminders | reschedule),
 * so an out-of-whitelist key cannot be expressed at the type level — defence in
 * depth alongside the server-side allow-list.
 */

export function useAutomationFlags() {
  return useQuery(getGetAutomationFlagsQueryOptions());
}

export function useAutomationToggle() {
  const qc = useQueryClient();

  const setFlag = useCallback(
    async (key: 'reminders' | 'reschedule', enabled: boolean) => {
      await setAutomationFlag(key, { enabled });
      await qc.invalidateQueries({ queryKey: ['automation'] });
    },
    [qc],
  );

  const flags = useAutomationFlags();

  const resume = useCallback(() => {
    for (const flag of flags.data?.flags ?? []) {
      if (!flag.enabled) void setFlag(flag.key, true);
    }
  }, [flags.data?.flags, setFlag]);

  return { flags, setFlag, resume };
}

/**
 * Renders nothing while automation is running. When paused it shows the
 * non-dismissible critical banner with a working Resume, per P17.1.
 */
export function AutomationPausedBanner() {
  const { flags, resume } = useAutomationToggle();

  // Fail-safe: never claim automation is fine based on a failed fetch, and never
  // cry wolf on a transient blip. We only surface the banner when we have
  // positively observed a disabled flag.
  const paused = flags.data?.paused === true;
  if (!paused) return null;

  return (
    <div className="sticky top-14 z-30 mx-auto w-full max-w-[1680px] px-4 pt-3 sm:px-6 lg:px-8 xl:px-10" data-testid="automation-paused-wrap">
      <SystemStatusBanner
        tone="critical"
        title="Automation paused"
        description="Reminders and auto-reschedule are off. Nothing will move or nudge you until you resume."
        action={{ label: 'Resume automation', onClick: resume }}
      />
    </div>
  );
}
