#!/usr/bin/env node
/**
 * Cadence design-token lint gate.
 *
 * docs/13-master-design-system-prompt.md P5.3:
 *   "Forbidden: arbitrary Tailwind values (bg-[#...], p-[13px], rounded-[7px]);
 *    hex/rgb in component files; inline style colors.
 *    Enforce with a lint rule or a CI grep — a failing check, not a guideline."
 *
 * This is that failing check. It exits 1 when a rule is violated.
 *
 * Design decisions:
 *  - shadcn/ui primitives under components/ui/** are EXEMPT. They are vendored
 *    upstream code regenerated by `shadcn add`; enforcing on them would make the
 *    gate impossible to satisfy without forking the library.
 *  - Severity is per-rule. `offenses` is the count that fails the build.
 *    Use --report to print everything without failing.
 *  - New code is expected to be clean. Legacy debt is baselined via
 *    docs/audit/.../token-lint-baseline.json and shrinks over time.
 *
 * Usage:
 *   node scripts/lint-tokens.cjs            # fail on any NEW offense
 *   node scripts/lint-tokens.cjs --report   # print all offenses, always exit 0
 *   node scripts/lint-tokens.cjs --no-baseline  # fail on ALL offenses
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'artifacts', 'cadence', 'src');
const BASELINE_FILE = path.join(
  ROOT, 'docs', 'audit', '2026-09-30-design-system-audit', 'token-lint-baseline.json',
);

const REPORT_ONLY = process.argv.includes('--report');
const NO_BASELINE = process.argv.includes('--no-baseline');
const WRITE_BASELINE = process.argv.includes('--write-baseline');

const RULES = [
  {
    id: 'no-hex-in-component',
    severity: 'error',
    spec: 'P5.3',
    why: 'hex in component files is forbidden; use a semantic token',
    test: (line) => /#[0-9A-Fa-f]{3,8}\b/.test(line),
  },
  {
    id: 'no-raw-rgb-in-component',
    severity: 'error',
    spec: 'P5.3',
    why: 'raw rgb()/rgba() in component files; use a semantic token',
    test: (line) => /\brgba?\(\s*\d/.test(line),
  },
  {
    id: 'no-arbitrary-color-value',
    severity: 'error',
    spec: 'P5.3',
    why: 'arbitrary Tailwind color value; use a token utility',
    test: (line) => /\b(?:bg|text|border|ring|fill|stroke|from|to|via|shadow|outline|divide|caret|decoration)-\[#[0-9A-Fa-f]{3,8}\]/.test(line),
  },
  {
    id: 'no-off-system-tailwind-palette',
    severity: 'error',
    spec: 'P6.3',
    why: 'off-system palette color; semantic colors may not be repurposed (P6.3 semantic exclusivity)',
    test: (line) =>
      /\b(?:bg|text|border|ring|fill|stroke|from|to|via|outline|divide)-(?:emerald|green|red|orange|amber|yellow|indigo|violet|purple|blue|sky|cyan|teal|rose|pink|lime|fuchsia)-[0-9]{2,3}\b/.test(line),
  },
  {
    id: 'no-sub-12px-text',
    severity: 'error',
    spec: 'P7',
    why: 'P7 type.caption (12px) is the floor; P8.4 repeats it for density',
    test: (line) => /\btext-\[(?:[0-9]|1[01])px\]/.test(line),
  },
  {
    id: 'no-arbitrary-font-size',
    severity: 'warn',
    spec: 'P5.3',
    why: 'arbitrary font-size; use the P7 type scale (text-caption ... text-timer)',
    test: (line) => /\btext-\[(?!.*(?:var\(--cell-size\)|--cell-size))[\d.]+(?:px|rem|em)\]/.test(line),
  },
  {
    id: 'no-unwrapped-css-var',
    severity: 'error',
    spec: 'Tailwind v4',
    why: 'Tailwind v4 removed the -[--var] shorthand; this emits invalid CSS that the browser discards',
    test: (line) => /-\[--[a-zA-Z0-9_-]+\]/.test(line),
  },
  {
    id: 'no-undersized-tap-target',
    severity: 'warn',
    spec: 'P8.1',
    why: '44x44px minimum tap target; add .tap-target-expand if the visual box must stay small',
    test: (line) => /<button|<a\s|<Link\s/.test(line) && /\b(?:size|h|w|min-h|min-w)-(?:[1-9]|10)\b/.test(line),
  },
];

function walk(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === 'ui') continue; // vendored shadcn primitives are exempt
      if (e.name === 'generated') continue; // generated clients (Orval) are exempt
      out.push(...walk(p));
    } else if (/\.(tsx|ts)$/.test(e.name)) {
      // GENERATED FILES ARE EXEMPT. This rule set targets hand-written source
      // only. Linting generator output is meaningless and actively wrong here:
      // styles/tokens.generated.ts is the canonical materialization of
      // tokens/tokens.json, so its hex literals ARE the design tokens. Flagging
      // them would demand we delete the design system. The file was previously
      // invisible to this scanner only because it was syntactically invalid
      // (a broken header comment), which is not a property worth relying on.
      if (/\.generated\.(ts|tsx)$/.test(e.name)) continue;
      out.push(p);
    }
  }
  return out;
}

const files = walk(SRC);
const offenses = [];

for (const f of files) {
  const rel = path.relative(ROOT, f).replace(/\\/g, '/');
  const lines = fs.readFileSync(f, 'utf8').split(/\r?\n/);
  lines.forEach((line, i) => {
    for (const rule of RULES) {
      if (rule.test(line)) {
        offenses.push({
          rule: rule.id,
          severity: rule.severity,
          spec: rule.spec,
          file: rel,
          line: i + 1,
          why: rule.why,
          excerpt: line.trim().slice(0, 90),
        });
      }
    }
  });
}

// --- baseline: suppress known legacy debt, fail only on NEW offenses ---------
// Baseline keys intentionally EXCLUDE the line number. Inserting an import or a
// few lines of JSX shifts every line below it, and a line-numbered baseline would
// then report a large file's entire pre-existing debt as "new" after any edit.
// Instead we key on rule + file + excerpt and compare COUNTS (multiset), so a
// file can legitimately have N instances of the same violation baselined, and
// adding an N+1th instance of that exact text still fails.
let baseline = {};
if (!NO_BASELINE && fs.existsSync(BASELINE_FILE)) {
  try {
    baseline = JSON.parse(fs.readFileSync(BASELINE_FILE, 'utf8'));
  } catch {
    console.error('warning: baseline file unreadable, treating as empty');
  }
}
function baselineKey(o) {
  return `${o.rule}|${o.file}|${o.excerpt}`;
}
const remaining = new Map();
for (const k of baseline.entries || []) {
  remaining.set(k, (remaining.get(k) || 0) + 1);
}
const fresh = [];
const freshSet = new Set();
for (const o of offenses) {
  const k = baselineKey(o);
  const left = remaining.get(k) || 0;
  if (left > 0) remaining.set(k, left - 1);
  else { fresh.push(o); freshSet.add(o); }
}
const errors = fresh.filter((o) => o.severity === 'error');
const warns = fresh.filter((o) => o.severity === 'warn');

// --- report -----------------------------------------------------------------
const byRule = {};
for (const o of offenses) {
  byRule[o.rule] = byRule[o.rule] || { total: 0, fresh: 0, severity: o.severity, spec: o.spec, why: o.why };
  byRule[o.rule].total++;
  if (freshSet.has(o)) byRule[o.rule].fresh++;
}

console.log('\nCadence token lint -- P5.3 enforcement gate');
console.log('='.repeat(72));
console.log(`scanned ${files.length} source files (components/ui/** exempt as vendored shadcn)\n`);
console.log(`${'rule'.padEnd(34)} ${'sev'.padEnd(6)} ${'total'.padStart(6)} ${'new'.padStart(5)}  spec`);
console.log('-'.repeat(72));
for (const [id, s] of Object.entries(byRule)) {
  console.log(`${id.padEnd(34)} ${s.severity.padEnd(6)} ${String(s.total).padStart(6)} ${String(s.fresh).padStart(5)}  ${s.spec}`);
}
console.log('-'.repeat(72));

if (fresh.length) {
  console.log(`\nNEW violations (${fresh.length}):`);
  for (const o of fresh.slice(0, 40)) {
    console.log(`  ${o.severity === 'error' ? 'ERROR' : 'warn '} ${o.file}:${o.line}  [${o.rule}]`);
    console.log(`         ${o.excerpt}`);
  }
  if (fresh.length > 40) console.log(`  ... and ${fresh.length - 40} more`);
}

console.log('');
console.log(`legacy baselined: ${offenses.length - fresh.length}   new: ${fresh.length}   errors: ${errors.length}   warns: ${warns.length}`);

if (WRITE_BASELINE) {
  const entries = offenses.map(baselineKey);
  fs.mkdirSync(path.dirname(BASELINE_FILE), { recursive: true });
  fs.writeFileSync(
    BASELINE_FILE,
    `${JSON.stringify(
      {
        $comment:
          'Generated by: node scripts/lint-tokens.cjs --write-baseline\n' +
          'Known legacy design-token debt. The gate fails on any NEW violation.\n' +
          'Re-baseline only after deliberately fixing debt, never to silence a regression.',
        generatedAt: new Date().toISOString(),
        count: entries.length,
        entries: entries.sort(),
      },
      null,
      2,
    )}\n`,
  );
  console.log(`\nbaseline written: ${path.relative(ROOT, BASELINE_FILE)} (${entries.length} entries)`);
  process.exit(0);
}

if (REPORT_ONLY) {
  console.log('\n(--report: not failing)');
  process.exit(0);
}

if (errors.length > 0) {
  console.error(`\nFAIL -- ${errors.length} new error-level violation(s). Fix, or run with --report to inspect.`);
  process.exit(1);
}
console.log('\nPASS -- no new error-level violations.');
